### ISSUE TITLE
Doing more complex lookups

### ISSUE THREAD

**Issue by groob** [brian-brazil/snmp_exporter#2]
Hello, we spoke briefly about this in IRC , but I want to document the issue here properly.

We manage a large number of Meraki Access Points, which use a proprietary MIB. 
Documented [here](http://blog.danielpark.com.au/2013/03/29/meraki-mib-cheat-sheet) by someone. 

If we walk the `devName` table, `snmpwalk` returns a result like this:
`MERAKI-CLOUD-CONTROLLER-MIB::devName.0.24.10.39.106.2 = STRING: Gym`

This has been fixed in c423d05f67425e8d15a587beb0d7623d11e16295 with the addition of PhysAddress48 type, which will append the macaddress to the lookup. 

Now, things get more complex if we're trying to reference a specific interface on the device. 
An interface ID will be appended to the OID. 
```
MERAKI-CLOUD-CONTROLLER-MIB::devInterfaceSentPkts.0.24.10.39.93.88.0 = Counter32: 75766
MERAKI-CLOUD-CONTROLLER-MIB::devInterfaceSentPkts.0.24.10.39.93.88.2 = Counter32: 280098
MERAKI-CLOUD-CONTROLLER-MIB::devInterfaceSentPkts.0.24.10.39.93.88.3 = Counter32: 607046
``` 
We can query for the devName table with a lookup like 
```
    indexes:
      - labelname: devName
        type: PhysAddress48
        lookup: 1.3.6.1.4.1.29671.1.1.4.1.2
```
But if we want to also lookup something in the interface table instead, the lookup will fail:
```
      - labelname: devInterfaceName
        type: PhysAddress48
        lookup: 1.3.6.1.4.1.29671.1.1.5.1.3
```
As a temporary fix, I added `PhysAddress48AddIndex` as yet another type, I'm not sure if there's a better way to solve this.

**Comment by brian-brazil** [comment]
I've already got a solution in mind for this, basically extraction of table indexes and lookups needs to be  two separate stages.

**Comment by brian-brazil** [comment]
This should be covered with https://github.com/brian-brazil/snmp_exporter/commit/9e7613bbb4ec7ad7a307a1ce51441e5301a596e2

You can now specify a list of index to lookup by.
